"""initial migrations

Revision ID: b3f5b2dbc0ed
Revises: 
Create Date: 2023-08-16 00:57:55.377942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f5b2dbc0ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('gln_sucursal', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('gln_sucursal')
    )
    op.create_table('client',
    sa.Column('gln_cliente', sa.BigInteger(), nullable=False),
    sa.Column('names', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('gln_cliente')
    )
    op.create_table('exceptionlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('gtin_producto', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('gtin_producto')
    )
    op.create_table('uploads',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('folder', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('inventory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fecha_inventario', sa.Date(), nullable=True),
    sa.Column('gln_cliente', sa.BigInteger(), nullable=True),
    sa.Column('gln_sucursal', sa.BigInteger(), nullable=True),
    sa.Column('gtin_producto', sa.BigInteger(), nullable=True),
    sa.Column('inventario_final', sa.Integer(), nullable=True),
    sa.Column('precio_unidad', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gln_cliente'], ['client.gln_cliente'], ),
    sa.ForeignKeyConstraint(['gln_sucursal'], ['branch.gln_sucursal'], ),
    sa.ForeignKeyConstraint(['gtin_producto'], ['product.gtin_producto'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha_inventario', 'gln_cliente', 'gln_sucursal', 'gtin_producto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('uploads')
    op.drop_table('product')
    op.drop_table('exceptionlog')
    op.drop_table('client')
    op.drop_table('branch')
    # ### end Alembic commands ###
